name: Docker
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
env:
  IMAGE_NAME: image
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi
  push:
    needs: test
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: build latest image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:latest
      - name: Push to Docker Hub
        run:|
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}
        IMAGE_NAME=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]')
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [ [ "${{ github.ref }}" == "refs/tags/"* ] ] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        [ "$VERSION" == "main" ] && VERSION=latest
        docker tag $IMAGE_NAME:latest $IMAGE_NAME:$VERSIONx
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$VERSION