name: HTTP Test
on:
  push:
    branches:
      - feature/*
    tags:
      - v*
  pull_request:
env:
  IMAGE_NAME: numb95/gooni-api
  CONTAINER_NAME: gooni-api-test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build tests image
        run: docker build . --file Dockerfile -t $IMAGE_NAME
      - name: run test image
        run: docker run -d --name $CONTAINER_NAME -p 8080:8080 $IMAGE_NAME
      - name: get 200 status
        run: |
          curl http://127.0.0.1:8080
          curl --write-out '%{http_code}' --silent --output /dev/null http://127.0.0.1:8080 -f
